"""add indexes on task status, due_date, is_pinned and note is_pinned

Revision ID: 0ca1a763b1f5
Revises: 7a7188596d51
Create Date: 2026-08-24 21:21:52.926477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca1a763b1f5'
down_revision: Union[str, Sequence[str], None] = '7a7188596d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_note_is_pinned'), 'note', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_is_pinned'), 'task', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_is_pinned'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_note_is_pinned'), table_name='note')
    # ### end Alembic commands ###
