"""add cascade delete from user to project

Revision ID: 2080cc766b0d
Revises: 1401a868db71
Create Date: 2026-06-20 19:14:47.788371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2080cc766b0d'
down_revision: Union[str, Sequence[str], None] = '1401a868db71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_user_id_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_user_id_fkey'), 'project', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
