"""add deleted_at soft-delete column to project, task, note

Revision ID: 5eda1fb2473a
Revises: 4be6817a91f3
Create Date: 2026-07-05 11:25:04.634686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eda1fb2473a'
down_revision: Union[str, Sequence[str], None] = '4be6817a91f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deleted_at')
    op.drop_column('project', 'deleted_at')
    op.drop_column('note', 'deleted_at')
    # ### end Alembic commands ###
