"""add owner_id to project

Revision ID: 6e6dad280313
Revises: 5eda1fb2473a
Create Date: 2026-07-05 11:40:20.043470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6dad280313'
down_revision: Union[str, Sequence[str], None] = '5eda1fb2473a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('project_owner_id_fkey', 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_owner_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'owner_id')
    # ### end Alembic commands ###
